name: SonarQube

#For more info see https://github.com/marketplace/actions/sonarqube-scan
on:
 pull_request:
    branches:
      - main
 push:
    branches:
      - main 
jobs:

  sonarcloud-front:
     timeout-minutes: 10
     runs-on: ubuntu-latest
     defaults:
      run:
        working-directory: 'front'

     steps:
     - uses: actions/checkout@v3
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
         node-version: '18.x'
     - name: Install packages    
       working-directory: 'front'
       run: npm ci
     - name: Build package
       working-directory: 'front'
       run: npm run build --if-present
     - name: Run Test
       working-directory: 'front'
       run: npm test -- --watch=false --browsers=ChromeHeadless
     - uses: sonarsource/sonarqube-scan-action@master
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
       with:
         projectBaseDir: front
         # See https://github.com/SonarSource/sonarcloud-github-action
         args: >
          -Dsonar.organization=achmoye
          -Dsonar.projectKey=achmoye_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
         
     

  sonarcloud-back:
    timeout-minutes: 10
    name: sonarqube-build-back
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'back'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -X -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey='achmoye_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD' -Dsonar.projectName='bobapp'
   
